### PR TITLE
CI(rust): Build agains multiple rust versions

### PR DESCRIPTION
**Pull request by Kreyren**
thing

This merge request implements building agains Rust Stable, beta, nightly and minimal supported version (1.44.0) on ubuntu, windows and macos, enables colors in GitHub UI and optimized the build trigger to not waste processing resources and puts test into it's own file.

Credit: Cargo-make's CI https://github.com/sagiegurari/cargo-make/blob/master/.github/workflows/ci.yml

Signed-off-by: Jacob Hrbek <kreyren@fsfe.org>

### CODE REVIEW

**Comment by Kreyren** [comment]
Demo: https://github.com/Kreyren/orion-lang/pull/2

**Comment by Kreyren** [comment]
CC @Wafelack

**Comment by Wafelack** [comment]
Hello,

Your merge request has been accepted, thanks for contributing to Orion.

**Comment by leolios** [comment]
Thanks for adding the file generated by Github for continuous integration - quality is important today!

**Comment by Kreyren** [comment]
> Thanks for adding the file generated by Github for continuous integration - quality is important today!

Quality is critical :p

**Pull request merged**
